
# ---------------------------------------------------------------------------- #
# Location of calibration database
caldb: /media/Oceanus/work/Observing/data/SHOC/calibration/

# prefer SI based naming convention for telescopes eg: "1.9m" over "74in" 
metric_names:           True
empty_filter_string:    ∅

# ---------------------------------------------------------------------------- #
remote:
    write_rsync_script: True
    server:             astro.cape.saao.ac.za
    username:           Null


# ---------------------------------------------------------------------------- #
# logging
logging:
    console:
        level: debug
        catch: False
        format: >- # -  chomping indicator strips end newlines
            {elapsed:s|Bb}|
            {{{name}.{function}:s|green}:{line:d|orange}: <52}|
            {{level.name}: {message}:|{style}}
        section: |

            {0:━<{width}}
            {{level.name}: {message}:|B,teal}
            {0:━<{width}}
        repeats: |
            { ⤷ [Previous {n_messages} {n_repeats} in {t}]:|kB}

    file:
        level: debug
        rotation: 2Mb
        format:  >-  # {time:YYYY-MM-DD HH:mm:ss zz}
            {time:HH:mm:ss!UTC}|
            {name}.{function}:{line:d}|
            {level.name}: {message}
        
# ---------------------------------------------------------------------------- #
# console info styling
console:
    banner:
        show:       True
        format: |
            {{now:|B,darkgreen}: <{width:}}
            {logo}
            {{subtitle:|B,purple}: >{width}}
            {{version:|Bk}: >{width}}
        subtitle:   Photometry Pipeline
        fg:         [bold, blue]
        linestyle:  [-, bold]
        linecolor:  teal
        width:      Null

    colors:
        flat: cornflowerblue
        dark: tan
        

    cutouts: 
        title:          "Source image cutouts: {hdu.file.name:|c}"
        title_align:    <
        title_style:    [B, _]
        extend:         3
        statistics:     [com, flux, areas, roundness]

    products:
        title_style:
            bg:     darkgreen
            fg:     [lightgrey, B, _]
        header_style:
            bg:     lightgreen
            fg:     [darkslategrey, B]



# # ---------------------------------------------------------------------------- #
# caching:
#     regions:   

# ---------------------------------------------------------------------------- #
# GUI
gui: 
    title: pySHOC Photometry Pipeline GUI
    pos : N

# plotting
plotting: &plotting
    delay:      True
    cmap:       cmr.voltage_r

    # samples:
    segments:
        contours: 
            cmap:   cmr.pride
            lw:     1.5

        labels:
            offset: [4, 4]
            size:   10
            color:  w
            emboss: [1, k]

    # Sample thumbnails plot config
    thumbnails:
        # name: thumbnails.png
        figsize: [9, 7.5]
        title_kws:
            color:      w
            size:       xx-small
            fontweight: bold

    mosaic:
        # name: mosaic.png
        cmap:   cmr.chroma
        alpha:  0.35

# aliases
# plots: *plotting
# plotting: *plotting


# ---------------------------------------------------------------------------- #
# Folder structure for pipeline results
folders:
    # root folder name default (if not provided by user at cli)
    output_root:    .pyshoc
    # The folder structure defined here will be created inside `output_root`
    info:           info
    logs:           $INFO/logs
    plots:          plots
    sample_images:  $PLOTS/sample_images
    registry:       reg
    phot:           phot/$HDU
    tracking:       $PHOT/track
    cache:          .cache

# Filenames for pipeline data products. 
# The folder paths defined above can be accessed below by eg $NAME for the `folders.name` field
files: &filenames
    # campaign info
    summary:        $INFO/campaign-files.xlsx
    products:       $INFO/data-products.xlsx
    obslog:         $INFO/observing-log.tex
    headers:        $PHOT/$HDU/header.txt

    # remote file retrieval
    remote:         $INFO/remote-files.txt
    rsync_script:   $INFO/rsync-remote.sh
    
    # image registration (wcs)
    registry: &reg 
        file:       $REGISTRY/registry.pkl
        params:     $REGISTRY/params.npy
    reg: *reg       # alias
    drizzle:        $REGISTRY/drizzle.fits

    # image plots
    thumbs:         $PLOTS/thumbnails.png
    thumbs_cal:     $PLOTS/thumbnails-cal.png
    mosaic:         $PLOTS/mosaic.png

    # source tracking data files
    tracking:
        measurements:       $TRACKING/centroids.dat       # (n, nstats, nsources, 2)
        coords:             $TRACKING/coords.dat          # (nsources, 2) structured ['xy', 'std']
        frame_info:         $TRACKING/frame-info.dat      # (n, 2)        structured
        source_info:        $TRACKING/source-info.dat     # (n, nsources) structured
        feature_weights:    $TRACKING/feature-weights.dat # (nstats, 1, 1)
        source_weights:     $TRACKING/source-weights.dat  # nsources  

# aliases
# filenames: *filenames


# ---------------------------------------------------------------------------- #
# sampled image stats
samples:
    stat:               median
    min_depth:          10          # minimun simulated integration time (seconds)
    n_intervals:        1
    subset:             Null        # eg: 1000 for sample from first 1000
    save_as:            png
    # filename_template:  {hdu.file.stem}{interval?}.{save_as}
    

# ---------------------------------------------------------------------------- #
# source detection
detection: &source_detection
    algorithm:      sigma_threshold
    npixels:        5
    edge_cutoff:    3
    edge_fraction:  0.5
    monolithic:     False
    roundness:      Null    # !!python/tuple [0.5, 1.75]
    dilate:         2
    deblend:        True
    report:
        cutouts: True

# aliases
detect:          *source_detection #
# source_find:        *source_detection #
# source_detection:   *source_detection #

# ---------------------------------------------------------------------------- #
# image registration 
registration: &image_registration
    survey:         dss
    fov_stretch:    1.65
    plot:           False
    fit_angle:      True
    # sigma_fallback: 10

drizzle: 
    pixfrac:        0.5

# ---------------------------------------------------------------------------- #
# source tracking 
tracking:
    dilate:             2
    circularize:        True
    njobs:              -1
    
    centroids:
        # features used for tracking
        com:                            1
        geometric_median:               1
        peak:               
            upsample: 1     # note, changing this will siginificantly affect compute times
            filter: lanczos

    pre_subtract:       True
    # subtract background from image prior to computing features
    bg:                 median
    # statistic used for background
    
    precision:          0.5
    # Required positional accuracy in pixels
    weights:            snr 
    # Per-source weights for frame offset calculation. Use "snr" for
    # signal-to-noise weighting.

    cutoffs:
        edge:           0
        snr:            3.
        # Sources with signal-to-noise ratio less than this will not be 
        # considered when solving for image dither
        distance:       10
        # For outlier detection: maximum distance allowed for point measurements
        # from centre of distribution.
        saturation:     95
        # If we know the saturation value of the CCD chip, we discard pixels above
        # this percentage of the saturation value

    compute:
        centres: [0 , 1000, 100 ]

    # ------------------------------------------------------------------------ #
    table:
        title:          Measured source coordinates
        title_style: 
            fg:         [B,  _,  w]
            bg:         darkslategrey
        col_head_style:
            fg:         [B,  _,  black]
            bg:         grey
        col_head_align: ^ 
        precision:      3
        align:          r
        row_nrs:        True
        max_rows:       25

    progress:
        bar_format: >-
            {{desc}: {percentage:3.0f}%{bar}{n_fmt}/{total_fmt}:|green}
            {rate_fmt:|gold}
            {elapsed:|cyan} eta {remaining:|cyan}
        ascii: " ╸━"
        unit:  " frames"
    
    # ------------------------------------------------------------------------ #
    plot:   True
    plots:

        centroids:
            com:              [r, +, "Centre of Mass"]
            geometric_median: [g, o, "Projected\n Geometric Median"]
            peak:             [m, ^, "Peak"]
            avg:              [k, x, "Weighted Centroid"] 
             # NOTE: avg sould be last

        labels:
            offset: [6, 6]
            color:  w
            size:   10
            # fontweight:bold

        position:
            figsize:            [12, 6.5]
            legend:             False
            show:               [avg, weights, caption]  #  nulls, pixel

            density:
                cmap:               null
                tessellation:       hex
                min_count:          3

            scatter:
                marker: x
                s:      5
                ls:     ''
                color:  null
                zorder: 1
                alpha:  0.35
            
            title:
                size:       13
                fontweight: bold
                pad:        10

            caption:
                pos:    [0.075, 0.01]
                text:   >-
                    $x_0 = {x:s}$
                    $y_0 = {y:s}$
                va:     bottom
                ha:     left
                bbox:       # these are matplotlib.patch.Patch properties
                    boxstyle:    round
                    facecolor:  lightgrey

            cbar:
                # shrink: 0.9
                pad:    0.01
                label0:  Counts
                label1:  Counts (Recentred)

            pixel: 
                lw:         0.75
                ls:         '--'
                fc:         none
                ec:         lime
                zorder:     100

            precision:
                lw:         0.75
                ls:         '--'
                fc:         none
                ec:         darkgreen
                zorder:     100